# Generated by Django 4.2.6 on 2024-04-27 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 27)),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='billdate',
            field=models.DateField(null=True),
        ),
    ]
